[package]
name = "vdrm-codec"
version = "0.1.0"
edition = "2021"

[dependencies]
plotters = "0.3"
plotters-cairo = "0.5"
gtk4 = "0.7"
lazy_static = "1.4"
neocortex = { version = "3.0.3", features = ["semaphore"] }
